version: '3.8'

services:

  react.app:
    container_name: react-app
    hostname: react.app
    build:
      context: ./Frontend
    ports:
      - "53001:5173"
    environment:
      "PUBLIC_PORT": "53001"
    networks:
      - frontend

  api.gateway:
    container_name: api-gateway
    build:
      context: ./Backend
      dockerfile: Gateway/Dockerfile
    ports:
      - "52001:8080"
    networks:
      - frontend
      - data-service
    restart: on-failure

  consumer.hadoop:
    container_name: consumer-hadoop
    build:
      context: ./Backend
      dockerfile: HadoopConsumer/Dockerfile
    networks:
      - data-service
    depends_on:
      - rabbitmq
    restart: on-failure

  producer.metadata:
    container_name: producer-data
    build:
      context: ./Backend
      dockerfile: DatabaseRegistry/Dockerfile
    ports:
      - "51001:8080"
    networks:
      - data-service
    depends_on: 
      - rabbitmq
    restart: on-failure

  service.analyser:
    container_name: service-analyser
    build:
      context: ./Backend
      dockerfile: VideoAnalyser/Dockerfile
    ports:
      - "51011:8080"
    networks:
      - data-service
    restart: on-failure

  producer.metadata.database:
    build:
      context: ./Backend/DatabaseRegistry/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - data-service

  rabbitmq: # login guest:guest 
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks:
      - data-service
    

networks:
  frontend:
  data-service: