version: '3.8'

services:
  react.app:
    container_name: react-app
    hostname: react.app
    build:
      context: ./Frontend
    ports:
      - "53001:5173"
    environment:
      "PUBLIC_PORT": "53001"
    networks:
      - frontend

  api.gateway:
    container_name: api-gateway
    build:
      context: ./Backend
      dockerfile: Gateway/Dockerfile
    ports:
      - "52001:80"
    networks:
      - frontend
      - data-service
  
  consumer.dummy:
    container_name: consumer-dummy
    build:
      context: ./Backend
      dockerfile: DummyConsumer/Dockerfile
    ports:
      - "51001:80"
    networks:
      - data-service

  producer.data:
    container_name: producer-data
    build:
      context: ./Backend
      dockerfile: MetadataProducer/Dockerfile
    ports:
      - "51002:80"
    networks:
      - data-service

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks:
      - data-service

networks:
  frontend:
  data-service: