@hostname=localhost
@port=52001
@endpointId=9801311b-4b40-4dfe-bde2-49e992b03625
@footageId=04fe00b74f

###
PUT http://{{hostname}}:{{port}}/gateway/create-endpoint
accept: text/plain
Content-Type: application/json

"Metadata"

###
GET http://{{hostname}}:{{port}}/gateway/list-endpoints
accept: text/plain

###
PUT http://{{hostname}}:{{port}}/gateway/update-endpoint
accept: text/plain
Content-Type: application/json

{
  "id": "{{endpointId}}",
  "name": "MongoDB"
}

###
DELETE http://{{hostname}}:{{port}}/gateway/delete-endpoint
accept: text/plain
Content-Type: application/json

{
  "id": "{{endpointId}}",
  "name": "Metadata"
}

###
POST http://{{hostname}}:{{port}}/gateway/get-metadata/{{footageId}}
accept: text/plain
Content-Type: application/json

"faces,topics,labels,keywords,namedLocations,namedPeople,shots,transcript"

###
POST http://{{hostname}}:{{port}}/gateway/add-metadata/{{endpointId}}
accept: text/plain
Content-Type: application/json

{
  "id": "04fe00b74f",
  "publishedUrl": "https://api.videoindexer.ai/internals/northeurope/Accounts/5eab727f-f7af-439b-b6ce-439b5b72a2f0/Videos/04fe00b74f/streaming-manifest/manifest.m3u8",
  "insights": {
    "faces": [
      {
        "id": 1477,
        "name": "Unknown #1",
        "confidence": 0,
        "thumbnailId": "e579946a-4082-4f75-8a91-0523b86adfec",
        "instances": [
          {
            "start": "0:00:01.56",
            "end": "0:00:32.64"
          },
          {
            "start": "0:02:41.08",
            "end": "0:02:48.28"
          },
          {
            "start": "0:02:48.48",
            "end": "0:02:49"
          }
        ]
      },
      {
        "id": 1303,
        "name": "Unknown #2",
        "confidence": 0,
        "thumbnailId": "5cdf48ac-3537-4f8a-a00c-f72793032214",
        "instances": [
          {
            "start": "0:01:29.64",
            "end": "0:01:38.76"
          },
          {
            "start": "0:01:44.68",
            "end": "0:01:52.4"
          },
          {
            "start": "0:02:29.72",
            "end": "0:02:41.08"
          }
        ]
      },
      {
        "id": 1166,
        "name": "Unknown #3",
        "confidence": 0,
        "thumbnailId": "959600b2-4a97-4ffe-922a-67d2b2135419",
        "instances": [
          {
            "start": "0:00:21.8",
            "end": "0:00:31.32"
          },
          {
            "start": "0:00:32.64",
            "end": "0:00:40.84"
          },
          {
            "start": "0:00:59.96",
            "end": "0:01:04.24"
          },
          {
            "start": "0:02:26",
            "end": "0:02:27.36"
          }
        ]
      },
      {
        "id": 1165,
        "name": "Unknown #4",
        "confidence": 0,
        "thumbnailId": "73e6536f-16e3-49b7-8501-e263a7809a65",
        "instances": [
          {
            "start": "0:00:21.76",
            "end": "0:00:31.36"
          },
          {
            "start": "0:00:32.64",
            "end": "0:00:37.48"
          },
          {
            "start": "0:00:38",
            "end": "0:00:40.84"
          },
          {
            "start": "0:00:59.96",
            "end": "0:01:04.24"
          },
          {
            "start": "0:02:26",
            "end": "0:02:27.36"
          }
        ]
      },
      {
        "id": 1328,
        "name": "Unknown #5",
        "confidence": 0,
        "thumbnailId": "f71e0587-15f1-46ce-89cd-e0789351cc6f",
        "instances": [
          {
            "start": "0:00:40.84",
            "end": "0:00:45.36"
          },
          {
            "start": "0:01:24",
            "end": "0:01:25.32"
          },
          {
            "start": "0:01:54.24",
            "end": "0:01:57.96"
          },
          {
            "start": "0:01:58.08",
            "end": "0:02:00.36"
          },
          {
            "start": "0:02:05.76",
            "end": "0:02:09"
          },
          {
            "start": "0:02:17.28",
            "end": "0:02:19.72"
          },
          {
            "start": "0:02:26.92",
            "end": "0:02:28.84"
          }
        ]
      },
      {
        "id": 1432,
        "name": "Unknown #6",
        "confidence": 0,
        "thumbnailId": "08c7e090-a354-4c0c-97c6-05ff4c06af27",
        "instances": [
          {
            "start": "0:01:25.92",
            "end": "0:01:29.64"
          },
          {
            "start": "0:02:29.72",
            "end": "0:02:41.08"
          }
        ]
      },
      {
        "id": 1237,
        "name": "Unknown #7",
        "confidence": 0,
        "thumbnailId": "fbbc7e53-9999-40d3-ad04-54decd1ad69c",
        "instances": [
          {
            "start": "0:00:45.36",
            "end": "0:00:48.36"
          },
          {
            "start": "0:00:50.96",
            "end": "0:00:52.68"
          },
          {
            "start": "0:01:12.64",
            "end": "0:01:19.92"
          },
          {
            "start": "0:02:03.72",
            "end": "0:02:05.76"
          }
        ]
      },
      {
        "id": 1397,
        "name": "Unknown #8",
        "confidence": 0,
        "thumbnailId": "3eb8b3b9-25a9-45d0-8490-9d6f39fe8ee3",
        "instances": [
          {
            "start": "0:02:05.76",
            "end": "0:02:09"
          },
          {
            "start": "0:02:16.32",
            "end": "0:02:26"
          }
        ]
      },
      {
        "id": 1368,
        "name": "Unknown #9",
        "confidence": 0,
        "thumbnailId": "494730e3-6f62-4a97-be09-fdba19139fa6",
        "instances": [
          {
            "start": "0:02:13.4",
            "end": "0:02:26"
          }
        ]
      },
      {
        "id": 1352,
        "name": "Unknown #10",
        "confidence": 0,
        "thumbnailId": "497b05cf-1f42-4f66-b28f-e4ef63016479",
        "instances": [
          {
            "start": "0:02:13.4",
            "end": "0:02:26"
          }
        ]
      },
      {
        "id": 1238,
        "name": "Unknown #11",
        "confidence": 0,
        "thumbnailId": "9a1b1afc-751c-4e02-a24c-c10bbbc12280",
        "instances": [
          {
            "start": "0:00:50.96",
            "end": "0:00:52.68"
          },
          {
            "start": "0:01:12.64",
            "end": "0:01:19.92"
          },
          {
            "start": "0:02:03.72",
            "end": "0:02:05.76"
          }
        ]
      },
      {
        "id": 1184,
        "name": "Unknown #12",
        "confidence": 0,
        "thumbnailId": "539e3167-9f07-45b1-9443-a206b050670d",
        "instances": [
          {
            "start": "0:00:44.12",
            "end": "0:00:45.36"
          },
          {
            "start": "0:01:04.24",
            "end": "0:01:12.64"
          }
        ]
      },
      {
        "id": 1183,
        "name": "Unknown #13",
        "confidence": 0,
        "thumbnailId": "b6eabc7d-4176-4c57-b87c-bdbb32828043",
        "instances": [
          {
            "start": "0:01:04.24",
            "end": "0:01:12.64"
          }
        ]
      }
    ],
    "topics": [
      {
        "id": 1,
        "name": "Technology",
        "referenceId": "Education/Technology",
        "confidence": 0.7348,
        "iptcName": "science and technology",
        "iabName": "Education",
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:19.52",
            "end": "0:02:46.64"
          }
        ]
      },
      {
        "id": 2,
        "name": "Games",
        "referenceId": "Games and Gaming/Games",
        "confidence": 0.5853,
        "iptcName": "lifestyle and leisure/leisure/game/video game",
        "iabName": "Hobbies & Interests",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02.08",
            "end": "0:01:00.64"
          },
          {
            "start": "0:01:19.52",
            "end": "0:02:46.64"
          }
        ]
      }
    ],
    "labels": [
      {
        "id": 1,
        "name": "person",
        "referenceId": "person",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02",
            "end": "0:00:16.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:37.04"
          },
          {
            "start": "0:00:39",
            "end": "0:00:39.04"
          },
          {
            "start": "0:00:44",
            "end": "0:00:48.04"
          },
          {
            "start": "0:00:51",
            "end": "0:00:52.04"
          },
          {
            "start": "0:00:56",
            "end": "0:01:19.04"
          },
          {
            "start": "0:01:26",
            "end": "0:01:38.04"
          },
          {
            "start": "0:01:43",
            "end": "0:01:52.04"
          },
          {
            "start": "0:01:59",
            "end": "0:02:00.04"
          },
          {
            "start": "0:02:04",
            "end": "0:02:08.04"
          },
          {
            "start": "0:02:14",
            "end": "0:02:48.04"
          }
        ]
      },
      {
        "id": 2,
        "name": "human face",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02",
            "end": "0:00:07.04"
          },
          {
            "start": "0:00:09",
            "end": "0:00:19.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:37.04"
          },
          {
            "start": "0:00:51",
            "end": "0:00:52.04"
          },
          {
            "start": "0:01:00",
            "end": "0:01:19.04"
          },
          {
            "start": "0:01:28",
            "end": "0:01:29.04"
          },
          {
            "start": "0:01:32",
            "end": "0:01:37.04"
          },
          {
            "start": "0:01:44",
            "end": "0:01:52.04"
          },
          {
            "start": "0:02:04",
            "end": "0:02:05.04"
          },
          {
            "start": "0:02:14",
            "end": "0:02:17.04"
          },
          {
            "start": "0:02:19",
            "end": "0:02:25.04"
          },
          {
            "start": "0:02:30",
            "end": "0:02:48.04"
          }
        ]
      },
      {
        "id": 3,
        "name": "clothing",
        "referenceId": "consumer goods/clothing",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02",
            "end": "0:00:16.04"
          },
          {
            "start": "0:00:20",
            "end": "0:00:20.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:37.04"
          },
          {
            "start": "0:00:45",
            "end": "0:00:47.04"
          },
          {
            "start": "0:00:51",
            "end": "0:00:51.04"
          },
          {
            "start": "0:00:56",
            "end": "0:01:19.04"
          },
          {
            "start": "0:01:26",
            "end": "0:01:38.04"
          },
          {
            "start": "0:01:43",
            "end": "0:01:52.04"
          },
          {
            "start": "0:02:00",
            "end": "0:02:00.04"
          },
          {
            "start": "0:02:04",
            "end": "0:02:08.04"
          },
          {
            "start": "0:02:14",
            "end": "0:02:26.04"
          },
          {
            "start": "0:02:30",
            "end": "0:02:48.04"
          }
        ]
      },
      {
        "id": 4,
        "name": "tie",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02",
            "end": "0:00:18.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:32.04"
          },
          {
            "start": "0:02:42",
            "end": "0:02:48.04"
          }
        ]
      },
      {
        "id": 5,
        "name": "man",
        "referenceId": "person/man",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:03",
            "end": "0:00:03.04"
          },
          {
            "start": "0:00:17",
            "end": "0:00:20.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:32.04"
          },
          {
            "start": "0:01:26",
            "end": "0:01:29.04"
          },
          {
            "start": "0:01:43",
            "end": "0:01:44.04"
          },
          {
            "start": "0:01:48",
            "end": "0:01:49.04"
          },
          {
            "start": "0:02:14",
            "end": "0:02:21.04"
          },
          {
            "start": "0:02:23",
            "end": "0:02:23.04"
          },
          {
            "start": "0:02:45",
            "end": "0:02:45.04"
          }
        ]
      },
      {
        "id": 6,
        "name": "text",
        "referenceId": "communication/writing/text",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:04",
            "end": "0:00:17.04"
          },
          {
            "start": "0:00:38",
            "end": "0:00:43.04"
          },
          {
            "start": "0:00:53",
            "end": "0:00:56.04"
          },
          {
            "start": "0:01:02",
            "end": "0:01:04.04"
          },
          {
            "start": "0:01:08",
            "end": "0:01:08.04"
          },
          {
            "start": "0:01:14",
            "end": "0:01:14.04"
          },
          {
            "start": "0:01:18",
            "end": "0:01:18.04"
          },
          {
            "start": "0:01:20",
            "end": "0:01:25.04"
          },
          {
            "start": "0:01:27",
            "end": "0:01:27.04"
          },
          {
            "start": "0:01:37",
            "end": "0:01:37.04"
          },
          {
            "start": "0:01:39",
            "end": "0:01:44.04"
          },
          {
            "start": "0:01:58",
            "end": "0:01:58.04"
          },
          {
            "start": "0:02:01",
            "end": "0:02:03.04"
          },
          {
            "start": "0:02:05",
            "end": "0:02:05.04"
          },
          {
            "start": "0:02:09",
            "end": "0:02:11.04"
          },
          {
            "start": "0:02:34",
            "end": "0:02:34.04"
          }
        ]
      },
      {
        "id": 7,
        "name": "suit",
        "referenceId": "consumer goods/clothing/suit",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:04",
            "end": "0:00:04.04"
          },
          {
            "start": "0:00:17",
            "end": "0:00:17.04"
          },
          {
            "start": "0:00:22",
            "end": "0:00:22.04"
          },
          {
            "start": "0:00:28",
            "end": "0:00:28.04"
          },
          {
            "start": "0:00:31",
            "end": "0:00:31.04"
          }
        ]
      },
      {
        "id": 8,
        "name": "cartoon",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:18",
            "end": "0:00:21.04"
          }
        ]
      },
      {
        "id": 9,
        "name": "computer",
        "referenceId": "device/machine/computer",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:37",
            "end": "0:00:37.04"
          },
          {
            "start": "0:00:41",
            "end": "0:00:41.04"
          },
          {
            "start": "0:00:46",
            "end": "0:00:48.04"
          },
          {
            "start": "0:00:56",
            "end": "0:00:57.04"
          },
          {
            "start": "0:01:00",
            "end": "0:01:00.04"
          },
          {
            "start": "0:01:02",
            "end": "0:01:06.04"
          },
          {
            "start": "0:01:08",
            "end": "0:01:08.04"
          },
          {
            "start": "0:01:10",
            "end": "0:01:12.04"
          },
          {
            "start": "0:01:30",
            "end": "0:01:31.04"
          },
          {
            "start": "0:01:38",
            "end": "0:01:38.04"
          },
          {
            "start": "0:01:40",
            "end": "0:01:41.04"
          },
          {
            "start": "0:01:52",
            "end": "0:01:52.04"
          },
          {
            "start": "0:02:02",
            "end": "0:02:03.04"
          },
          {
            "start": "0:02:09",
            "end": "0:02:11.04"
          },
          {
            "start": "0:02:18",
            "end": "0:02:18.04"
          },
          {
            "start": "0:02:25",
            "end": "0:02:29.04"
          }
        ]
      },
      {
        "id": 10,
        "name": "indoor",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:38",
            "end": "0:00:40.04"
          },
          {
            "start": "0:00:45",
            "end": "0:00:48.04"
          },
          {
            "start": "0:00:57",
            "end": "0:01:12.04"
          },
          {
            "start": "0:01:30",
            "end": "0:01:38.04"
          },
          {
            "start": "0:01:44",
            "end": "0:01:57.04"
          },
          {
            "start": "0:01:59",
            "end": "0:02:00.04"
          },
          {
            "start": "0:02:06",
            "end": "0:02:08.04"
          },
          {
            "start": "0:02:14",
            "end": "0:02:28.04"
          },
          {
            "start": "0:02:36",
            "end": "0:02:41.04"
          }
        ]
      },
      {
        "id": 11,
        "name": "display device",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:41",
            "end": "0:00:42.04"
          }
        ]
      },
      {
        "id": 12,
        "name": "output device",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:42",
            "end": "0:00:42.04"
          },
          {
            "start": "0:00:44",
            "end": "0:00:44.04"
          }
        ]
      },
      {
        "id": 13,
        "name": "laptop",
        "referenceId": "computer/portable computer/laptop",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:44",
            "end": "0:00:45.04"
          },
          {
            "start": "0:00:48",
            "end": "0:00:48.04"
          },
          {
            "start": "0:01:00",
            "end": "0:01:00.04"
          },
          {
            "start": "0:01:05",
            "end": "0:01:07.04"
          },
          {
            "start": "0:01:09",
            "end": "0:01:12.04"
          },
          {
            "start": "0:02:26",
            "end": "0:02:26.04"
          },
          {
            "start": "0:02:28",
            "end": "0:02:29.04"
          }
        ]
      },
      {
        "id": 14,
        "name": "smile",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:51",
            "end": "0:00:51.04"
          },
          {
            "start": "0:01:38",
            "end": "0:01:38.04"
          },
          {
            "start": "0:01:45",
            "end": "0:01:45.04"
          }
        ]
      },
      {
        "id": 15,
        "name": "furniture",
        "referenceId": "furniture",
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:58",
            "end": "0:00:59.04"
          },
          {
            "start": "0:01:58",
            "end": "0:01:58.04"
          },
          {
            "start": "0:02:06",
            "end": "0:02:08.04"
          }
        ]
      },
      {
        "id": 16,
        "name": "wall",
        "referenceId": "structure/wall",
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:31",
            "end": "0:01:31.04"
          },
          {
            "start": "0:01:45",
            "end": "0:01:45.04"
          },
          {
            "start": "0:01:55",
            "end": "0:01:57.04"
          },
          {
            "start": "0:02:20",
            "end": "0:02:20.04"
          },
          {
            "start": "0:02:22",
            "end": "0:02:25.04"
          }
        ]
      },
      {
        "id": 17,
        "name": "desk",
        "referenceId": "furniture/table/desk",
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:59",
            "end": "0:01:59.04"
          }
        ]
      },
      {
        "id": 18,
        "name": "woman",
        "referenceId": "person/woman",
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:07",
            "end": "0:02:08.04"
          }
        ]
      },
      {
        "id": 19,
        "name": "wheel",
        "referenceId": "device/mechanical device/wheel",
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:12",
            "end": "0:02:12.04"
          }
        ]
      },
      {
        "id": 20,
        "name": "tire",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:12",
            "end": "0:02:12.04"
          }
        ]
      },
      {
        "id": 21,
        "name": "transport",
        "referenceId": "conveyance/transport",
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:12",
            "end": "0:02:12.04"
          }
        ]
      },
      {
        "id": 22,
        "name": "personal computer",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:27",
            "end": "0:02:28.04"
          }
        ]
      },
      {
        "id": 23,
        "name": "businessperson",
        "referenceId": null,
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:42",
            "end": "0:02:47.04"
          }
        ]
      }
    ],
    "keywords": [
      {
        "id": 1,
        "text": "coding pirates",
        "confidence": 0.9726,
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:53.2",
            "end": "0:02:21.08"
          },
          {
            "start": "0:01:02",
            "end": "0:01:05.04"
          },
          {
            "start": "0:01:09",
            "end": "0:01:11.04"
          },
          {
            "start": "0:01:15",
            "end": "0:01:17.04"
          },
          {
            "start": "0:02:15",
            "end": "0:02:18.04"
          }
        ]
      },
      {
        "id": 2,
        "text": "pirates",
        "confidence": 0.7398,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:38.04",
            "end": "0:01:00.64"
          },
          {
            "start": "0:01:53.2",
            "end": "0:02:21.08"
          },
          {
            "start": "0:02:29.84",
            "end": "0:02:46.64"
          },
          {
            "start": "0:01:02",
            "end": "0:01:05.04"
          },
          {
            "start": "0:01:09",
            "end": "0:01:11.04"
          },
          {
            "start": "0:01:15",
            "end": "0:01:17.04"
          },
          {
            "start": "0:02:15",
            "end": "0:02:18.04"
          }
        ]
      },
      {
        "id": 3,
        "text": "computer",
        "confidence": 0.7217,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:07.56",
            "end": "0:00:27.88"
          },
          {
            "start": "0:01:20.2",
            "end": "0:01:43.48"
          },
          {
            "start": "0:01:22",
            "end": "0:01:25.04"
          }
        ]
      },
      {
        "id": 4,
        "text": "anders",
        "confidence": 0.6321,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:04",
            "end": "0:00:30.04"
          },
          {
            "start": "0:01:33",
            "end": "0:01:36.04"
          }
        ]
      },
      {
        "id": 5,
        "text": "kode",
        "confidence": 0.6211,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:04",
            "end": "0:00:30.04"
          },
          {
            "start": "0:01:20",
            "end": "0:01:24.04"
          }
        ]
      }
    ],
    "namedPeople": [
      {
        "id": 1,
        "name": "Yang",
        "tags": [],
        "confidence": 0.76,
        "instances": [
          {
            "start": "0:00:38.04",
            "end": "0:01:00.64"
          }
        ]
      }
    ],
    "namedLocations": [
      {
        "id": 1,
        "name": "school",
        "tags": [],
        "confidence": 0.65,
        "instances": [
          {
            "start": "0:01:20.2",
            "end": "0:01:43.48"
          }
        ]
      }
    ],
    "shots": [
      {
        "id": 1,
        "keyFrames": [
          {
            "id": 1,
            "instances": [
              {
                "thumbnailId": "43b87524-91ad-43a7-b708-4a2ffb937fa2",
                "start": "0:00:00.2",
                "end": "0:00:00.24"
              }
            ]
          },
          {
            "id": 2,
            "instances": [
              {
                "thumbnailId": "e8ee676e-d293-47d9-9f93-4595ca5e0a2a",
                "start": "0:00:00.28",
                "end": "0:00:00.32"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:00",
            "end": "0:00:01.4"
          }
        ],
        "tags": null
      },
      {
        "id": 2,
        "keyFrames": [
          {
            "id": 3,
            "instances": [
              {
                "thumbnailId": "e23466f4-9d4f-4a48-a9f3-f05fc35534ca",
                "start": "0:00:01.68",
                "end": "0:00:01.72"
              }
            ]
          },
          {
            "id": 4,
            "instances": [
              {
                "thumbnailId": "3724c7fd-2fc1-4a17-96b6-145d2c94e49a",
                "start": "0:00:17.2",
                "end": "0:00:17.24"
              }
            ]
          },
          {
            "id": 5,
            "instances": [
              {
                "thumbnailId": "7250e6f6-7179-4a78-8cb2-d7fd0b034d76",
                "start": "0:00:31.4",
                "end": "0:00:31.44"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:01.64",
            "end": "0:00:32.64"
          }
        ],
        "tags": [
          "Medium",
          "CenterFace"
        ]
      },
      {
        "id": 3,
        "keyFrames": [
          {
            "id": 6,
            "instances": [
              {
                "thumbnailId": "f2ad24c9-b57e-46a6-bb2f-e9e9097c89d6",
                "start": "0:00:32.72",
                "end": "0:00:32.76"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:32.64",
            "end": "0:00:37.48"
          }
        ],
        "tags": [
          "CloseUp",
          "Medium"
        ]
      },
      {
        "id": 4,
        "keyFrames": [
          {
            "id": 7,
            "instances": [
              {
                "thumbnailId": "d6c069fb-31fd-4453-babf-ebb541a764ac",
                "start": "0:00:37.8",
                "end": "0:00:37.84"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:37.48",
            "end": "0:00:40.84"
          }
        ],
        "tags": [
          "Medium",
          "CenterFace"
        ]
      },
      {
        "id": 5,
        "keyFrames": [
          {
            "id": 8,
            "instances": [
              {
                "thumbnailId": "e878ecf4-a085-46f1-904f-bdb2dcefbb64",
                "start": "0:00:40.92",
                "end": "0:00:40.96"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:40.84",
            "end": "0:00:44.12"
          }
        ],
        "tags": [
          "Medium",
          "LeftFace"
        ]
      },
      {
        "id": 6,
        "keyFrames": [
          {
            "id": 9,
            "instances": [
              {
                "thumbnailId": "aaa560c5-7fae-4559-9c37-0e19d63192f7",
                "start": "0:00:44.2",
                "end": "0:00:44.24"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:44.12",
            "end": "0:00:45.36"
          }
        ],
        "tags": [
          "Medium"
        ]
      },
      {
        "id": 7,
        "keyFrames": [
          {
            "id": 10,
            "instances": [
              {
                "thumbnailId": "ead1aa2a-c895-4db4-9fe9-1a7e3f39c782",
                "start": "0:00:45.68",
                "end": "0:00:45.72"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:45.36",
            "end": "0:00:48.36"
          }
        ],
        "tags": [
          "Medium",
          "LeftFace"
        ]
      },
      {
        "id": 8,
        "keyFrames": [
          {
            "id": 11,
            "instances": [
              {
                "thumbnailId": "1b291db6-4e42-441a-a9fa-ff0fddbab18b",
                "start": "0:00:48.68",
                "end": "0:00:48.72"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:48.36",
            "end": "0:00:50.96"
          }
        ],
        "tags": null
      },
      {
        "id": 9,
        "keyFrames": [
          {
            "id": 12,
            "instances": [
              {
                "thumbnailId": "bb1e7395-5e78-4c25-b6a0-2ccb6dd3449f",
                "start": "0:00:51.04",
                "end": "0:00:51.08"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:50.96",
            "end": "0:00:52.68"
          }
        ],
        "tags": [
          "CloseUp"
        ]
      },
      {
        "id": 10,
        "keyFrames": [
          {
            "id": 13,
            "instances": [
              {
                "thumbnailId": "57b6ec4c-3d45-4251-9a0f-32361055693f",
                "start": "0:00:52.76",
                "end": "0:00:52.8"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:52.68",
            "end": "0:00:55.8"
          }
        ],
        "tags": null
      },
      {
        "id": 11,
        "keyFrames": [
          {
            "id": 14,
            "instances": [
              {
                "thumbnailId": "e4a10d0f-3d3e-45e7-9f49-54b62afabc60",
                "start": "0:00:55.88",
                "end": "0:00:55.92"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:55.8",
            "end": "0:00:58"
          }
        ],
        "tags": null
      },
      {
        "id": 12,
        "keyFrames": [
          {
            "id": 15,
            "instances": [
              {
                "thumbnailId": "d1f0c82e-7e2f-465e-8a4d-9c9eea931c6f",
                "start": "0:00:58.32",
                "end": "0:00:58.36"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:58",
            "end": "0:00:59.96"
          }
        ],
        "tags": null
      },
      {
        "id": 13,
        "keyFrames": [
          {
            "id": 16,
            "instances": [
              {
                "thumbnailId": "ae543b95-acf3-4c41-8a92-6eed0f5917ef",
                "start": "0:01:00.04",
                "end": "0:01:00.08"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:00:59.96",
            "end": "0:01:04.24"
          }
        ],
        "tags": [
          "CloseUp",
          "Medium"
        ]
      },
      {
        "id": 14,
        "keyFrames": [
          {
            "id": 17,
            "instances": [
              {
                "thumbnailId": "93d70607-be2c-4b0e-bb8e-dc0269b7141b",
                "start": "0:01:04.56",
                "end": "0:01:04.6"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:04.24",
            "end": "0:01:12.64"
          }
        ],
        "tags": [
          "Wide",
          "Medium"
        ]
      },
      {
        "id": 15,
        "keyFrames": [
          {
            "id": 18,
            "instances": [
              {
                "thumbnailId": "faff6cdb-9521-496d-9119-e7930b74a661",
                "start": "0:01:12.72",
                "end": "0:01:12.76"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:12.64",
            "end": "0:01:19.92"
          }
        ],
        "tags": [
          "Medium"
        ]
      },
      {
        "id": 16,
        "keyFrames": [
          {
            "id": 19,
            "instances": [
              {
                "thumbnailId": "8499fc79-121a-4db9-b14f-86feffb8d1b2",
                "start": "0:01:20.24",
                "end": "0:01:20.28"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:19.92",
            "end": "0:01:25.92"
          }
        ],
        "tags": null
      },
      {
        "id": 17,
        "keyFrames": [
          {
            "id": 20,
            "instances": [
              {
                "thumbnailId": "3db99012-212b-4723-a43e-e3f14f7f77c9",
                "start": "0:01:26",
                "end": "0:01:26.04"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:25.92",
            "end": "0:01:29.64"
          }
        ],
        "tags": [
          "Wide",
          "Medium"
        ]
      },
      {
        "id": 18,
        "keyFrames": [
          {
            "id": 21,
            "instances": [
              {
                "thumbnailId": "c36ed8d6-1618-41a9-83b6-2ef594166c43",
                "start": "0:01:29.96",
                "end": "0:01:30"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:29.64",
            "end": "0:01:38.76"
          }
        ],
        "tags": [
          "Medium",
          "RightFace"
        ]
      },
      {
        "id": 19,
        "keyFrames": [
          {
            "id": 22,
            "instances": [
              {
                "thumbnailId": "c456c1b7-9e4d-47ea-b344-17fc090ddeac",
                "start": "0:01:39.08",
                "end": "0:01:39.12"
              }
            ]
          },
          {
            "id": 23,
            "instances": [
              {
                "thumbnailId": "5a0bc1d3-e957-487d-99ec-fb8f1e507d4f",
                "start": "0:01:40.84",
                "end": "0:01:40.88"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:38.76",
            "end": "0:01:42.4"
          }
        ],
        "tags": null
      },
      {
        "id": 20,
        "keyFrames": [
          {
            "id": 24,
            "instances": [
              {
                "thumbnailId": "e06650cd-53dd-437f-b33a-9e98140b37cf",
                "start": "0:01:42.48",
                "end": "0:01:42.52"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:42.4",
            "end": "0:01:44.68"
          }
        ],
        "tags": null
      },
      {
        "id": 21,
        "keyFrames": [
          {
            "id": 25,
            "instances": [
              {
                "thumbnailId": "d9ef0057-1de2-4341-93d7-1c874b0b6085",
                "start": "0:01:45",
                "end": "0:01:45.04"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:44.68",
            "end": "0:01:52.4"
          }
        ],
        "tags": [
          "Medium",
          "RightFace"
        ]
      },
      {
        "id": 22,
        "keyFrames": [
          {
            "id": 26,
            "instances": [
              {
                "thumbnailId": "5e45f378-2b06-494e-bf56-bfff949aa1a8",
                "start": "0:01:52.44",
                "end": "0:01:52.48"
              }
            ]
          },
          {
            "id": 27,
            "instances": [
              {
                "thumbnailId": "09e597c0-3582-44ab-9e5f-e0a1290dd9f7",
                "start": "0:01:55.84",
                "end": "0:01:55.88"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:52.4",
            "end": "0:01:57.96"
          }
        ],
        "tags": [
          "Wide",
          "RightFace"
        ]
      },
      {
        "id": 23,
        "keyFrames": [
          {
            "id": 28,
            "instances": [
              {
                "thumbnailId": "06ad79ae-77f6-42ab-b4b1-d1da93282122",
                "start": "0:01:58.24",
                "end": "0:01:58.28"
              }
            ]
          },
          {
            "id": 29,
            "instances": [
              {
                "thumbnailId": "bbe88954-c3a1-4840-b0e6-b301855490d9",
                "start": "0:01:59.32",
                "end": "0:01:59.36"
              }
            ]
          },
          {
            "id": 30,
            "instances": [
              {
                "thumbnailId": "b95683c7-c2df-44b7-89ef-072e95066c32",
                "start": "0:02:00.28",
                "end": "0:02:00.32"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:01:57.96",
            "end": "0:02:00.36"
          }
        ],
        "tags": [
          "Wide",
          "CenterFace",
          "Medium",
          "RightFace"
        ]
      },
      {
        "id": 24,
        "keyFrames": [
          {
            "id": 31,
            "instances": [
              {
                "thumbnailId": "bbe54888-5823-46d7-a610-86bc346dc656",
                "start": "0:02:00.44",
                "end": "0:02:00.48"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:00.36",
            "end": "0:02:01.72"
          }
        ],
        "tags": null
      },
      {
        "id": 25,
        "keyFrames": [
          {
            "id": 32,
            "instances": [
              {
                "thumbnailId": "242d2dfb-3cfb-4b05-85d1-72909ae9486c",
                "start": "0:02:02.04",
                "end": "0:02:02.08"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:01.72",
            "end": "0:02:03.72"
          }
        ],
        "tags": null
      },
      {
        "id": 26,
        "keyFrames": [
          {
            "id": 33,
            "instances": [
              {
                "thumbnailId": "cbd088fd-eca1-4924-9703-5691019c4d20",
                "start": "0:02:03.8",
                "end": "0:02:03.84"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:03.72",
            "end": "0:02:05.76"
          }
        ],
        "tags": [
          "Medium"
        ]
      },
      {
        "id": 27,
        "keyFrames": [
          {
            "id": 34,
            "instances": [
              {
                "thumbnailId": "77b1f0de-ef4e-4434-901e-d8be301f13c6",
                "start": "0:02:05.84",
                "end": "0:02:05.88"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:05.76",
            "end": "0:02:09"
          }
        ],
        "tags": [
          "Wide"
        ]
      },
      {
        "id": 28,
        "keyFrames": [
          {
            "id": 35,
            "instances": [
              {
                "thumbnailId": "afd6df7c-e285-489d-b98a-2ef40d1d0c19",
                "start": "0:02:09.32",
                "end": "0:02:09.36"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:09",
            "end": "0:02:11.12"
          }
        ],
        "tags": null
      },
      {
        "id": 29,
        "keyFrames": [
          {
            "id": 36,
            "instances": [
              {
                "thumbnailId": "b5f87fa2-7be0-45b3-9756-f069ee26c013",
                "start": "0:02:11.16",
                "end": "0:02:11.2"
              }
            ]
          },
          {
            "id": 37,
            "instances": [
              {
                "thumbnailId": "4b1eb571-bd08-4b17-bb94-4045f00731bb",
                "start": "0:02:12.76",
                "end": "0:02:12.8"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:11.12",
            "end": "0:02:13.4"
          }
        ],
        "tags": null
      },
      {
        "id": 30,
        "keyFrames": [
          {
            "id": 38,
            "instances": [
              {
                "thumbnailId": "b7b46135-6732-4d52-9b57-83cbcffebc40",
                "start": "0:02:13.72",
                "end": "0:02:13.76"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:13.4",
            "end": "0:02:26"
          }
        ],
        "tags": [
          "Wide",
          "Medium"
        ]
      },
      {
        "id": 31,
        "keyFrames": [
          {
            "id": 39,
            "instances": [
              {
                "thumbnailId": "73db0676-d2b3-4ba7-9f59-9251dcbf4a2b",
                "start": "0:02:26.68",
                "end": "0:02:26.72"
              }
            ]
          },
          {
            "id": 40,
            "instances": [
              {
                "thumbnailId": "a7e82d1c-b1e8-40db-b774-7eac2030666e",
                "start": "0:02:27.8",
                "end": "0:02:27.84"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:26",
            "end": "0:02:29.72"
          }
        ],
        "tags": [
          "Medium",
          "CloseUp",
          "RightFace"
        ]
      },
      {
        "id": 32,
        "keyFrames": [
          {
            "id": 41,
            "instances": [
              {
                "thumbnailId": "129162f3-c4df-41f3-bad9-49eb5071fdfa",
                "start": "0:02:30.04",
                "end": "0:02:30.08"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:29.72",
            "end": "0:02:41.08"
          }
        ],
        "tags": [
          "Medium"
        ]
      },
      {
        "id": 33,
        "keyFrames": [
          {
            "id": 42,
            "instances": [
              {
                "thumbnailId": "60b185de-f3ff-4bec-a741-fa6d5a7e2471",
                "start": "0:02:41.12",
                "end": "0:02:41.16"
              }
            ]
          },
          {
            "id": 43,
            "instances": [
              {
                "thumbnailId": "4d3318e1-8383-4d83-ab61-3d711fad11cd",
                "start": "0:02:42.88",
                "end": "0:02:42.92"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:41.08",
            "end": "0:02:48.28"
          }
        ],
        "tags": [
          "CloseUp",
          "CenterFace"
        ]
      },
      {
        "id": 34,
        "keyFrames": [
          {
            "id": 44,
            "instances": [
              {
                "thumbnailId": "97b9df66-cd07-425a-a421-4dd50b5f665f",
                "start": "0:02:48.6",
                "end": "0:02:48.64"
              }
            ]
          }
        ],
        "instances": [
          {
            "start": "0:02:48.28",
            "end": "0:02:49"
          }
        ],
        "tags": [
          "Wide",
          "LeftFace"
        ]
      }
    ],
    "transcript": [
      {
        "id": 1,
        "text": "Deflates the score of swiftor elite one another.",
        "confidence": 0.3945,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:02.08",
            "end": "0:00:04.64"
          }
        ]
      },
      {
        "id": 2,
        "text": "Gela, ETA de Musky Victista Sport.",
        "confidence": 0.2368,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:04.64",
            "end": "0:00:07.24"
          }
        ]
      },
      {
        "id": 3,
        "text": "Computer Critique for flair.",
        "confidence": 0.2749,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:07.56",
            "end": "0:00:27.88"
          }
        ]
      },
      {
        "id": 4,
        "text": "Some new.",
        "confidence": 0.3969,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:28.6",
            "end": "0:00:29.12"
          }
        ]
      },
      {
        "id": 5,
        "text": "Yang of interest in terms of sterling Pirates, he's not.",
        "confidence": 0.2485,
        "speakerId": 2,
        "language": "en-US",
        "instances": [
          {
            "start": "0:00:38.04",
            "end": "0:01:00.64"
          }
        ]
      },
      {
        "id": 6,
        "text": "The.",
        "confidence": 0.2469,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:19.52",
            "end": "0:01:19.6"
          }
        ]
      },
      {
        "id": 7,
        "text": "First of year, no more Computer Historia on school.",
        "confidence": 0.4187,
        "speakerId": 2,
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:20.2",
            "end": "0:01:43.48"
          }
        ]
      },
      {
        "id": 8,
        "text": "Mean.",
        "confidence": 0.3712,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:49.16",
            "end": "0:01:50.28"
          }
        ]
      },
      {
        "id": 9,
        "text": "I was coding pirates or choosing coding.",
        "confidence": 0.3604,
        "speakerId": 2,
        "language": "en-US",
        "instances": [
          {
            "start": "0:01:53.2",
            "end": "0:02:21.08"
          }
        ]
      },
      {
        "id": 10,
        "text": "Pirates for Student, Microsoft?",
        "confidence": 0.371,
        "speakerId": 1,
        "language": "en-US",
        "instances": [
          {
            "start": "0:02:29.84",
            "end": "0:02:46.64"
          }
        ]
      }
    ]
  }
}