apiVersion: v1
kind: Service
metadata:
  name: database-registry
spec:
  ports:
    -
      name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: database-registry-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-registry-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database-registry-pod
    spec:
      containers:
        - 
          image: {REGISTRY}/database-registry:{IMG_TAG}
          imagePullPolicy: Always
          name: database-registry
          ports:
            -
              containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 150m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /Data/Get
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: database-registry-store
spec:
  ports:
    -
      port: 3306
      targetPort: 3306
  selector:
    app: database-registry-store-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-registry-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-registry-store-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-registry-store-pod
    spec:
      containers:
        -
          args:
            - "--default-authentication-plugin=mysql_native_password"
          image: {REGISTRY}/database-registry-store:{IMG_TAG}
          name: mysql
          ports:
            -
              containerPort: 3306
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 400Mi
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: database-registry-persistent-storage
      volumes:
        -
          name: database-registry-persistent-storage
          persistentVolumeClaim:
            claimName: database-registry-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: database-registry-store-pod
  name: database-registry-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
