apiVersion: v1
kind: Service
metadata:
  name: metadata-hadoop-store
spec:
  ports:
    -
      name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: metadata-hadoop-store-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-hadoop-store-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-hadoop-store-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metadata-hadoop-store-pod
    spec:
      containers:
        - 
          image: {REGISTRY}/andrn19/tv2-cand-project/metadata-hadoop-store:{IMG_TAG}
          imagePullPolicy: Always
          name: metadata-hadoop-store
          ports:
            -
              containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        -
          name: regcred
