name: Build and deploy
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  REGISTRY: ghcr.io
  REGISTRY_NAME: ${{ github.repository }}
  SERVICE_CONTAINER_GROUP: video-analyser-service

jobs:
  build-and-deploy-registry-store:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: database-registry-store
    permissions:
      contents: read
      packages: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

          
      - name: Build and push Database Registry Store
        id: build-and-push-registry-store
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Backend/DatabaseRegistry/Database/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.SERVICE_CONTAINER_GROUP }}
          location: 'north europe'

  build-and-deploy-registry:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: database-registry
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Database Registry 
        id: build-and-push-registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Backend/
          file: ./Backend/DatabaseRegistry/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.SERVICE_CONTAINER_GROUP }}
          location: 'north europe'

  build-and-deploy-metadata-store:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: metadata-hadoop-store
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Hadoop Database 
        id: build-and-push-hadoop
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Backend/
          file: ./Backend/HadoopConsumer/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.SERVICE_CONTAINER_GROUP }}
          location: 'north europe'

  build-and-deploy-gateway:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: gateway
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Gateway 
        id: build-and-push-gateway
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Backend/
          file: ./Backend/Gateway/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.SERVICE_CONTAINER_GROUP }}
          location: 'north europe'

  build-and-deploy-video-analyser:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: video-analyser
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0


      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Build and push Video Analyser
        id: build-and-push-analyser
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Backend/
          file: ./Backend/VideoAnalyser/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.SERVICE_CONTAINER_GROUP }}
          location: 'north europe'
