name: Build and deploy
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  AZURE_CONTAINER_REGISTRY: MetadataAnalyser
  REGISTRY_NAME: andrn19/tv2-cand-project
  SERVICE_CONTAINER_GROUP: video-analyser-service
  AKS_CLUSTER: tv2-video-analyser-cluster
  

jobs:
  build-database-registry-store:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: database-registry-store
      CONTEXT: ./Backend/DatabaseRegistry/Database/
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}


  build-database-registry:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: database-registry
      CONTEXT: ./Backend/
      DOCKERFILE: ./Backend/DatabaseRegistry/Dockerfile
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --file ${{ env.DOCKERFILE }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}



  build-metadata-hadoop-store:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: metadata-hadoop-store
      CONTEXT: ./Backend/
      DOCKERFILE: ./Backend/HadoopConsumer/Dockerfile
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --file ${{ env.DOCKERFILE }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}



  build-gateway:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: gateway
      CONTEXT: ./Backend/
      DOCKERFILE: ./Backend/Gateway/Dockerfile
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --file ${{ env.DOCKERFILE }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}



  build-video-analyser:

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: video-analyser
      CONTEXT: ./Backend/
      DOCKERFILE: ./Backend/VideoAnalyser/Dockerfile
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --file ${{ env.DOCKERFILE }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}



  build-frontend:
  
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: frontend
      CONTEXT: ./Frontend/
      DOCKERFILE: ./Frontend/Dockerfile
    permissions:
      contents: read
      id-token: write
    
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.SERVICE_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} --file ${{ env.DOCKERFILE }} -g ${{ env.RESOURCE_GROUP }} ${{ env.CONTEXT }}



  deploy-kubernetes:
    runs-on: ubuntu-latest
    needs: [build-database-registry-store,build-database-registry,build-metadata-hadoop-store,build-gateway,build-video-analyser,build-frontend]

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks install-cli
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}
          kubectl create secret docker-registry regcred \
            --docker-server=${{ env.REGISTRY }} \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }}
          
      - name: Change deployment file image tags
        run: |
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/AnalyserService.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/DatabaseRegistry.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/Frontend.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/Gateway.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/MetadataHadoopStore.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/RabbitMQ.yaml

      - name: Deploy Container Instances
        run: kubectl apply -f Deployment/Kubernetes/
