name: Deploy
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_NAME: andrn19/tv2-cand-project
  SERVICE_CONTAINER_GROUP: video-analyser-service
  AKS_CLUSTER: tv2-video-analyser-cluster
  ACR_NAME: MetadataAnalyser
  

jobs:
  build-images-on-acr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Get AKS Credentials
        run: |
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/video-analyser:${{ github.SHA }} Backend/VideoAnalyser/
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/frontend:${{ github.SHA }} Frontend/
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/database-registry-store:${{ github.SHA }} Backend/DatabaseRegistry/Database/
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/gateway:${{ github.SHA }} Backend/Gateway/
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/metadata-hadoop-store:${{ github.SHA }} Backend/HadoopConsimer/
          az acr build --registry ${{ env.ACR_NAME }} --image ${{ env.REGISTRY_NAME }}/database-registry:${{ github.SHA }} Backend/DatabaseRegistry/


  deploy-kubernetes:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: |
          az aks install-cli
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}
          
      - name: Change deployment file image tags
        run: |
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/AnalyserService.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/DatabaseRegistry.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/Frontend.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/Gateway.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/MetadataHadoopStore.yaml
          sed -i "s+{IMG_TAG}+${{ github.sha }}+g" Deployment/Kubernetes/RabbitMQ.yaml

      - name: Deploy Container Instances
        run: kubectl apply -f Deployment/Kubernetes/
