name: Deploy ACR
on:
  workflow_dispatch:

env:
  AKS_CLUSTER: tv2-video-analyser-cluster
  

jobs:
  deploy-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER }}
          admin: 'false'
          use-kubelogin: 'true'
  
      - name: Deploy application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: Deployment/External/
