name: Build and Test React Application

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          
      - name: npm ci, build and test
        working-directory: ./Frontend
        run: |
          npm ci
          npm run build --if-present
          npm test
